import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { Resend } from "npm:resend"

// CORS headers for secure browser communication
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

serve(async (req) => {
  // Handle CORS preflight request
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    // 1. Securely retrieve the Resend API key from environment variables
    const resendApiKey = Deno.env.get("RESEND_API_KEY");
    if (!resendApiKey) {
      throw new Error("Missing RESEND_API_KEY environment variable.");
    }

    // Initialize the Resend client using npm:resend syntax
    const resend = new Resend(resendApiKey);

    // 2. Parse incoming JSON request body
    const payload = await req.json()
    
    // Support both direct client payloads and Supabase Database Webhook payloads (payload.record)
    const record = payload.record || payload;

    const name = record.name || record.Name || 'Unknown';
    const email = record.email || record.Email || 'No Email';
    const projectType = record.projecttype || record.project_type || record.subject || 'General Inquiry';
    const message = record.message || record.Message || 'No Message';

    // 3. Construct and send email using the Resend SDK
    const emailResponse = await resend.emails.send({
      from: "Shreeji Construction <onboarding@resend.dev>", // Replace with verified domain in production
      to: "shreejiconstruction2007@zohomail.in", // Recipient personal/corporate email
      subject: "New Project Inquiry",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; background-color: #ffffff;">
          <h2 style="color: #002147; border-bottom: 2px solid #e85d00; padding-bottom: 10px;">New Project Inquiry</h2>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #4a5568; width: 120px;">Name:</td>
              <td style="padding: 8px 0; color: #2d3748;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Email:</td>
              <td style="padding: 8px 0; color: #2d3748;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Project Type:</td>
              <td style="padding: 8px 0; color: #2d3748;">${projectType}</td>
            </tr>
          </table>

          <div style="background-color: #f7fafc; padding: 15px; border-left: 4px solid #e85d00; margin-top: 10px; border-radius: 4px;">
            <p style="margin: 0; font-weight: bold; color: #4a5568; margin-bottom: 5px;">Message:</p>
            <p style="margin: 0; color: #2d3748; white-space: pre-wrap; line-height: 1.5;">${message}</p>
          </div>
          
          <footer style="margin-top: 30px; font-size: 12px; color: #a0aec0; text-align: center; border-top: 1px solid #edf2f7; padding-top: 15px;">
            This email was automatically generated by the Supabase Database Webhook trigger.
          </footer>
        </div>
      `,
    })

    if (emailResponse.error) {
      throw new Error(`Resend Error: ${emailResponse.error.message}`);
    }

    return new Response(
      JSON.stringify({ success: true, data: emailResponse.data }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    )

  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    )
  }
})
